### ISSUE TITLE
[Question] RdlViewer - showing the parameters only used in the report

### ISSUE THREAD

**Issue by maratoss** [majorsilence/My-FyiReporting#100]
How can i show in RdlViewer only the parameters used in design mode?
Or how can i get the parameters in RdlViewer.cs which are using?

I just want to hide these unnecessary fields from UI, see screenshot
for example: if i use only "cell phone" field in the report then other fields has to be hided
![untitled](https://cloud.githubusercontent.com/assets/1102119/9376258/b6a06fc2-471b-11e5-8eb4-1e342e4508c5.png)

**Comment by Gankov** [comment]
What did you mean "used in design mode"?
If you didn't use some parameters in report, why are you don't just remove them?

Just now I find out that you can clean prompt and parameters without prompt will not be displayed.

**Comment by maratoss** [comment]
> What did you mean "used in design mode"?

"design mode" i meant this mode (where you can make your report), see screenshot
![untitled](https://cloud.githubusercontent.com/assets/1102119/9378594/bfff8a36-4733-11e5-9042-b625dd4f9687.png)


> If you didn't use some parameters in report, why are you don't just remove them?

I need to provide an opportunity to my users to make theirs own report and so each user desides which parameters he has to use. That's why i need to hide not used parameters from RdlViewer.
User doesn't want to see not used parameters in "Preview"

PS Parameters are same for each user, i put the parameters in the report by myself

**Comment by Gankov** [comment]
This is definitely not implemented. 
I am not sure that it need to be by default.
But, i can offer solution: before run report, you can dynamic parse XML, found all place where parameters used and remove prompt or remove not used parameter, or implement API in RdlViewer for setting visibility of parameters entries from your application. 
Like it made in GTKViewer for setting ConnectString https://github.com/majorsilence/My-FyiReporting/blob/master/RdlGtkViewer/RdlGtkViewer/RdlGtkViewer.cs#L393

**Comment by maratoss** [comment]
Ok, thanks, i'll try to make something
