### ISSUE TITLE
@PageNumber not incrementing

### ISSUE THREAD

**Issue by develop101** [majorsilence/My-FyiReporting#107]
Hi,
When I add the the a field @PageNumber to a report and preview the result, the Page number is always 1?

The @TotalPages seems to work correctly.

**Comment by Gankov** [comment]
Are you added @PageNumber in Footer\Header? or Body? By specification @PageNumber and @TotalPages should work only in Footer\Header. 
In last git version, i made @PageNumber to work in body too, but this is undocumented features and this is NOT included in RDL specification.
https://github.com/majorsilence/My-FyiReporting/commit/668d876e4ee86ac535a4c4f6ccac0444b1515600

**Comment by develop101** [comment]
I have tried @PageNumber in the Header and Footer. Is it worth getting the latest code out of the repository?

**Comment by Gankov** [comment]
Thanks for bug report.
