### ISSUE TITLE
Connection String in Datasources - Designer - Not evaluating 

### ISSUE THREAD

**Issue by hardsoft** [majorsilence/My-FyiReporting#117]
When using ={?p_connectionstring} as the data source in designer this expression is not evaluated by
1. The Test Connection button on DataSources form
2. Refresh Fields button on DataSet form

**Comment by chripf** [comment]
Pretty solution (reading the report's parameters) requires some work, these items are currently not available in the DataSources form. Fast solution might be having a second Textbox to define a development connection.
