### ISSUE TITLE
Embedded image in html

### ISSUE THREAD

**Issue by rjuergen** [majorsilence/My-FyiReporting#122]
Embedded images didn't work in html report.

**Comment by rjuergen** [comment]
The problem is the html converter just generates an image like this: 
`<img src="testHtml2.png" class='css2'/>`
testHtml is the name of the html file. no idea why the image is called like the html file.

In Html you can show an embedded image like this: 
`<img src="data:image/png;/*here is the embedded image code like in the rdl file*/" >`
It's important in html that there is at the begining of the src "data:image/png;". In common rdl you have the node "MIMEType" with "image/png".
The embedded image code from the rdl file is not in the html file. It's just ignored.

Example embedded image:
`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD0AAABACAIAAAAmvOihAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAMKSURBVGhD7ZixihVBEEX9Fr/H3/AvjMwNjQxNjAQxMTAxEU1kIzeRxWBFWBRFWRCTZ0HXDm1N3ztVXTULD97lssFuvZmz03Orq9+dw3HqxH27OnHf6MP387sv7q39+ut7rahQPfej86eGuPn+u4daUaFi7m9/fhjc3h9/XmhdWsXczz6/Mqy9n3x6rnVpVXL/+nttQNeWBdHqnCq5USJ7V6WzkvvB2WNDuXZVOsu4L35fGkTkknSWcfNE9i5JZw23J5G98+ms4X57dWbImtEelE9nDbekzZA1o3XIp7OAW3JmsJpfXr6Rv6L3PpnOAm7JmWFq/nJ9JX+Vn+b3zcl0ZrnRQCK9XCvwW5RJZ5ZbEmZomiWpWoFTm0lnltugLJZEagUdErUirhQ3Gkgki1pxI5QBuYJWBJXiRu153SvQfyhX0Iqg5rnR6qPebMoWz6Vznhs1ZpQ2VN/afFST3GQgQc8PNXKxVkQ0yT33vqJGPpHOSW50ROAEZPzSCrdmuMkRQSuASCOPpnOGGyVs3bbXQo08ms4wN0lkG6S40PAo1gqfwtzoHfWP1OaDi0PpDHOjntAPUlzySpjPNofSGeMmq9wPUlykkfvTGeNGqYoeAlAb9aczwE26WPTQhUIi1ootBbjREcGfyEWkKTnTGeA2N1g8NxihV86ZTi83GkjE0a2uiUTcc0EvtzwGc/X97FlAFzdJ5E7WG2O5uNFAsp8307nNTbK/nzfTuc1NEikDbdKot4p5Ore50d4W3SOHIovJ07nBLY/EXG5xdI9EIuHRipE2uNFFJ/ZIJPJoSDoZ9/QiRoVm4/7LUSPGTaafuT0SidwInaEYN3oME8dvLrKvoTMr5Cbzg3NkCwmNWeLhiQRyRy+UVPQxjbknFi4vc6PFw3SOuck25vmyYU7So8y9Fq9vOuY2H1tc2LbXCi3ygJsMJP4vG+aEZgqxCdWAmxwR9khkL/LITDotN1mskkGKi+zQJp2Wm0w5VYMUFwHo0/kfN/l3d01kLzJm9ekcvN9HoRP37eo4uQ+Hf8znq/4iYM+3AAAAAElFTkSuQmCC" >`

**Comment by rjuergen** [comment]
Please help :D. The source of the My-FyiReporting is a little bit confusing for a newbie of the project.

**Comment by majorsilence** [comment]
I am not 100% certain but I believe you want to look at https://github.com/majorsilence/My-FyiReporting/blob/master/RdlEngine/Render/RenderHtml.cs or maybe https://github.com/majorsilence/My-FyiReporting/blob/master/RdlEngine/Render/HtmlConverter/RenderHtmlTable.cs.

Search for "img src=" to find the areas that need to be changed.

**Comment by rjuergen** [comment]
Thanks for the help. I have fixed it, but I don't have the permission to commit.

Here is the patch:
[patch.txt](https://github.com/majorsilence/My-FyiReporting/files/129296/patch.txt)

**Comment by majorsilence** [comment]
Great.  Thanks for the patch.  I can merge it or you can also create a fork and send a pull request.

**Comment by rjuergen** [comment]
Would be great if you can merge it.

**Comment by majorsilence** [comment]
The patch looks fine.  I'll review it again and then merge it.

**Comment by rjuergen** [comment]
it's working. thank you!
issue can be closed.
