### ISSUE TITLE
Parameters containing ampersand (&) breaks report

### ISSUE THREAD

**Issue by chripf** [majorsilence/My-FyiReporting#129]
I am using filters filled by a selection from database - putting the name of an entity into the filterstring in this particular case. Sometimes the name contains an **ampersand (&)**, which breaks the parameter string. Escaping the ampersand is not an option because there is no unescaping in the rdl-viewer.

The `ParameterString`-Property in `RdlViewer.cs`  has to stay like it is to avoid breaking existing implementations. I am considering three approaches:

1. Introducing a second parameter e.g. `JsonParameters `using a JSON format ([JSON .NET](http://www.newtonsoft.com/json) does a good job there).
2. Introducing a flag `ParameterFormat` defaulting to the current implementation and put the code into the existing property.
3. Try to parse the incoming string as JSON and fall back to current implementation.

Personally I think Option 1 is to be preferred.

**Comment by Gankov** [comment]
I like 1 case.
I think it more flexibly for adding another parameters formats, like simple array or dictionary.

**Comment by chripf** [comment]
Thinking over it again, it mayb e better to add a method for setting the parameters - for the sake of readability.

    public void SetReportParametersAsJson(string jsonString){
        _Parameters = JsonConvert.DeserializeObject<Dictionary<string, string>>(jsonString);
    }

Makes it even more clear what happens and there could be other methods like `SetReportParametersAsXml(string xmlString)` or `AddSingleReportParameter(string key, string value)`.

**Comment by Gankov** [comment]
Сould be so.
