### ISSUE TITLE
Unify interfaces of the various viewer implementations

### ISSUE THREAD

**Issue by dfyx** [majorsilence/My-FyiReporting#131]
For an application that I'm building (currently WPF but we plan to add Cocoa and GTK# in the future) I need to load the RDL files from embedded resources and fill the reports with data that's computed at runtime.

With the WinForms `RdlViewer` class that's pretty easy to achieve:

``` csharp
var dataTable = new DataTable();
dataTable.Columns.Add("CategoryID");
dataTable.Columns.Add("CategoryName");
dataTable.Columns.Add("Description");

for (var i = 0; i < 10; i++)
{
    dataTable.Rows.Add(i, "Foo", "Lorem Ipsum");
}

var assembly = typeof(MainWindow).Assembly;

using (var stream = assembly.GetManifestResourceStream("ReportingTest.test.rdl"))
using (var reader = new StreamReader(stream))
{
    RdlViewer.SourceRdl = reader.ReadToEnd();
}

RdlViewer.Report.DataSets["Data"].SetData(dataTable);
RdlViewer.Rebuild();
```

The `RdlWpfViewer` class doesn't allow direct access to its `.Report` which would be trivial to add.

As far as I can see, the interfaces for `LibRdlCrossPlatformViewer.ReportViewer` and `RdlGtkViewer` are completely different from those two, having neither an equivalent to `.SourceRdl` nor to `.Report`.

**Comment by majorsilence** [comment]
You can download dlls to test with from https://ci.appveyor.com/project/majorsilence/my-fyireporting/build/artifacts.

Please note the LibRdlCrossPlatformViewer is experimental and has less features then the winforms reviewer.

**Comment by dfyx** [comment]
Thanks for your quick reply.

- The WPF Viewer is perfect now.
- There's still some slight difference in behavior for the XWT viewer. To be fully compatible, The `SourceRdl` setter should automatically call `Rebuild` to be compatible with the other implementations.
