### ISSUE TITLE
npgsql asembly error

### ISSUE THREAD

**Issue by chandan4871** [majorsilence/My-FyiReporting#147]
when trying to connect the postgresql using report designer it is showing reference assembly error npgsql not found please help

**Comment by Gankov** [comment]
See in file RdlEngineConfig.xml
What path to dll setup in Postgres section?
If like this 
>          <CodeModule>Npgsql.dll</CodeModule>
then you need have Npgsql.dll library in program folder. Or you can set full path to Npgsql.dll.

**Comment by chandan4871** [comment]
It is written like this <DataSource>
         <DataProvider>PostgreSQL</DataProvider>
         <CodeModule>Npgsql.dll</CodeModule>
         <ClassName>Npgsql.NpgsqlConnection</ClassName>
         <TableSelect>SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME NOT LIKE 'pg_%' ORDER BY 1</TableSelect>
         <Interface>SQL</Interface>
      </DataSource>

**Comment by Gankov** [comment]
> If like this
>  `<CodeModule>Npgsql.dll</CodeModule>`
>then you need have Npgsql.dll library in program folder.

**Comment by chandan4871** [comment]
it is written like this   <CodeModule>Npgsql.dll</CodeModule>.I have also paste the Npgsql.dll file in the root folder but still not working

**Comment by chandan4871** [comment]
![errorreport](https://cloud.githubusercontent.com/assets/8778102/20659445/a6f55728-b569-11e6-871c-b8c8753f7260.png)

Above image is showing the file structure of the report designer kindly help

**Comment by chandan4871** [comment]
but which one is the program folder??

**Comment by chandan4871** [comment]
@Gankov but which one is the program folder

**Comment by Gankov** [comment]
This is sems ok. Should works.

**Comment by chandan4871** [comment]
@Gankov yes but not working

**Comment by chandan4871** [comment]
@Gankov 
![errorreport](https://cloud.githubusercontent.com/assets/8778102/20659924/aff6abf8-b56c-11e6-9866-c7e3f6fbf641.png)


This error is coming

**Comment by Gankov** [comment]
I use only mysql and if i put dll beside RdlEngine.dll. This always work.
Try use Process Monitor http://download.sysinternals.com/files/ProcessMonitor.zip to define where RDLEngine try search postgres library.
