### ISSUE TITLE
PDF Report Japanese and Chinese reports ?

### ISSUE THREAD

**Issue by doerler** [majorsilence/My-FyiReporting#152]
Is it possible to generate PDF reports with Japanese and Chinese Charakters. They look fine in the designer, but the generated reports are not showing them. The old PDF Output method doesn't show the right characters. 

Is this just a report issue (correct font) or is there a bigger problem with My-FyiReporting supporting chinese and japanese reports ?

**Comment by doerler** [comment]
I've found the problem - the Arial fonts (which are used in RenderPdf_iTextSharp) don't support Japanese or Chinese characters.

I've added this function
```
public bool IsAsian(string[] text)
{
    bool asian = false;
    for (var i = 0; i < text.Length; ++i)
    {
        asian |= text[i].Any(c => c >= 0x4e00);
        if (asian)
        {
            break;
        }
    }
    return asian;
}
```
and changed the function AddText (line 374):
```
else if (face == "Arial")
{
    if (si.IsFontBold() && si.FontStyle == FontStyleEnum.Italic)
    if (IsAsian(sa))
    {
        face = "Arial Unicode MS";
        fontname = "arialuni.ttf";
    }
    else if (si.IsFontBold() && si.FontStyle == FontStyleEnum.Italic)
```
Not the most elegant way to solve this problem, but maybe it helps somebody else.

**Comment by majorsilence** [comment]
Open a pull request and I'll merge in the changes.

**Comment by doerler** [comment]
Created pull request:
https://github.com/majorsilence/My-FyiReporting/pull/153

**Comment by doerler** [comment]
the pull request was missing two Japanese scripts. Opened a new pull request: https://github.com/majorsilence/My-FyiReporting/pull/154

**Comment by majorsilence** [comment]
great.  thanks.

**Comment by psoares33** [comment]
My fix allows the use of other CJK fonts, I think this can be closed.
