### ISSUE TITLE
.net core 2.0

### ISSUE THREAD

**Issue by ravtakhar** [majorsilence/My-FyiReporting#167]
Do you guys have any plans to make this project compatible with .net core 2.0?

Whenever I attempt to export to pdf I get the following error: 

Could not load type 'System.Drawing.Bitmap' from assembly 'System.Drawing'
I believe this is due to .net core 2.0 not supporting System.Drawing.Bitmap.

Edit:
I need the "Core" library just needs to be rebuilt using "CoreCompact.System.Drawing" and targeted at .net core 2.0 instead of .net 4.0

**Comment by majorsilence** [comment]
I see no problem with adding this.  Send a pull request with the changes.

**Comment by psoares33** [comment]
This requires changes in itextsharp, it's not that trivial and will probably break "normal" .NET.

**Comment by ravtakhar** [comment]
Closing this issue because I no longer need this functionality.
