### ISSUE TITLE
Barcode interleaved 2 of 5

### ISSUE THREAD

**Issue by chripf** [majorsilence/My-FyiReporting#169]
Would be great to have support for barcodes of type [interleaved 2 of 5 (ITF)](https://en.wikipedia.org/wiki/Interleaved_2_of_5).

**Comment by chripf** [comment]
https://github.com/barnhill/barcodelib looks promising.

**Comment by chripf** [comment]
Did a basic implementation for the ITF-14 code. However I believe using the barcodelib package one could make a pretty generic support for quite a range of barcodes. Might better be placed in a new Issue thou.

**Comment by majorsilence** [comment]
I am open to using barcodelib for a larger range of barcodes.
