### ISSUE TITLE
Can I use datasource from external dll file?

### ISSUE THREAD

**Issue by whitesorrow** [majorsilence/My-FyiReporting#188]
Hi I have the dll file to get the data from the database (return as dictionary or something else) 
how can I use it for create the report in designer? 
is it possible to use dll file to get the data from database instead of sql query?

Thank you

**Comment by Kernel-Klink** [comment]
Not sure about in the designer, but at runtime you can set the data from
code.  FAQ here:
https://github.com/majorsilence/My-FyiReporting/tree/master/Examples/SampleApp2-SetData

The Kernel

**Comment by whitesorrow** [comment]
How can I create the report file if I didn't have it currently use designer -> empty report or use rdlviewer
Sorry for simple question but I didn't find the document for reference

Thank you
