### ISSUE TITLE
Can I show one id per page ?

### ISSUE THREAD

**Issue by whitesorrow** [majorsilence/My-FyiReporting#189]
Hi ,
if I have data with id like this

id   name   desc
1     aaa     ccc
1    bbb    ccc
2   aaa      bbb
2   bbb     bbb

I have two table in one page
first table
id --- 1
desc ccc

second table show all with id = 1
 id   name  desc
 1   aaa    ccc
 1   bbb   ccc

 for normally the table will display all row
if I need to display id 1 in first page and id 2 in second page is it possible?

**Comment by Kernel-Klink** [comment]
The way I have done this before is use a list (might be able to do it with
a table) as a "master" for the page.  Size this appropriately so it take
the entire page; this forces each subsequent item to kick to a new page.
Select Distinct IDs; use these to feed a sub-report.

The sub-report would take the ID as a report input parameter; each
sub-report fires a query that contains that parameter in the predicate (ID
in this case).  This would display the data associated with that ID.

Some many not like this solution as it will fire more queries than a
filtering option.  I agree.  On the flip side it is easy to implement and
most reports don't require high performance.

The Kernel

**Comment by Kernel-Klink** [comment]
This wiki
<https://github.com/majorsilence/My-FyiReporting/wiki/0001---Create-New-Report>
shows how to create a Report with a Report Parameter.  We'll call this the
sub report; ensure it when you run it and provide the input ID, it only
shows you the data you want to see for that ID.

Open the "master report" you can insert a sub report from the "Insert" menu
in the designer.  The configuration dialog will allow you to pass data to
the input parameters of the sub report.

[image: image.png]

The Kernel

**Comment by whitesorrow** [comment]
Hi Kernel-Klink ,

I had add the parameter in subreport and can pass the parameter value from mainreport to subreport
but when I go to dataset -> SQL select it can get only query parameter that I can't pass from mainreport
is there syntax to use parameter in the sql?

ex. query parameter use '@parametername' but for parameter I didn't found it from SQL... button

ps. the image image.png I can't see it.

Thank you

**Comment by whitesorrow** [comment]
never mind I can do it now

query parameter
id --> =!parameter.param_id.value
parameter (can pass from mainreport)
param_id

SQL
where id = @id
