### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by orellabac** [majorsilence/My-FyiReporting#195]
Hi. I have created a branch with support for .NET Core how can I push this branch and summit a PR ?

**Comment by Gankov** [comment]
I think, yes.

**Comment by majorsilence** [comment]
Follow the instructions found at https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by orellabac** [comment]
Thanks!. I created a PR https://github.com/majorsilence/My-FyiReporting/pull/196 for this

**Comment by majorsilence** [comment]
I've merged in your pull request.
