### ISSUE TITLE
Possible missing DLL

### ISSUE THREAD

**Issue by wyllson** [majorsilence/My-FyiReporting#198]
While testing version 4.14.  RdlDesigner.exe (file save)... i get the following error:

Could not load file or assembly 'EncryptionProvider. Version=1.0.0.0. Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
at fyiReporting.RdlDesign.MDIChild.doPossibleEncrytion(Uri file, String rdl)
at fyiReporting.RdlDesign.MDIChild.FileSave(Uri file, String rdl)

**Comment by majorsilence** [comment]
this should be fixed in 4.15

https://github.com/majorsilence/My-FyiReporting/releases/tag/version_4.15
