### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Gankov** [majorsilence/My-FyiReporting#208]
@majorsilence Can you release Majorsilence Reporting? Last release was very long ago. We had some improves in code.

**Comment by majorsilence** [comment]
New releases have been made.  Projects have been updated to sdk style projects.  New nugget packages and zips of the apps have been made.   With the changes put in places doing release builds aee simplified.   No new gtk 2 builds have been made as I'm having problems with tbe old references.  There is a new gtk 3 project targetting net6.0 and 8.0 but it has problems sustem.drawing.  I am attempting to work with a DrawingCompat library but am running into libgdiplus runtime problems.
