### ISSUE TITLE
How to merge some row  cell like excel?Can you add this function

### ISSUE THREAD

**Issue by njsunsky** [majorsilence/My-FyiReporting#227]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Gankov** [comment]
You can do it for row only. Merge multi cells in one on one row.
![span](https://github.com/majorsilence/My-FyiReporting/assets/451041/c9a78a0c-92b5-4362-9cb5-a3fff26596f9)

You can't do vertical merge, for cells from different rows. 
But you can make visual format like is merged cells by settings of borders.
![different_cells](https://github.com/majorsilence/My-FyiReporting/assets/451041/27fc3111-dabb-443d-942d-d5a8bcf8dfe7)

**Comment by njsunsky** [comment]
Thanks @Gankov ,you are right,if can not vertical merge,your suggest is the best way
