### ISSUE TITLE
Linux Patch to xmutil.cs on commit #9f245643 dated 26/04/2024 prevent color usage on Windows System

### ISSUE THREAD

**Issue by alberti47** [majorsilence/My-FyiReporting#233]
function  ColorFromHtml has been patched to return FIXED color.Acqua.
The patch prevent on Windows to properly translate Html color.
I dont' have information about the reason of this patch.
I will Pull a request for cancel the patch unless different advise
Regards

**Comment by majorsilence** [comment]
That sounds like incorrect behaviour in the code.

Send the pull request.

**Comment by majorsilence** [comment]
It is bad code.  I should not of comitted it.
