### ISSUE TITLE
Alignment problem on render pdf files

### ISSUE THREAD

**Issue by NelsonSantos** [majorsilence/My-FyiReporting#79]
Hi... 

I have made some reports with render to PDF and some times the alignment of columns on table or textbox are printed with desalignment.

On attachment I put a sample about the issue.

There are some workaround do to on this, or is a bug?

Regards.

Nelson Santos
![pdf_render](https://f.cloud.github.com/assets/3474662/2278918/2d73d95a-9f60-11e3-90af-1998f2879d72.jpg)

**Comment by psoares33** [comment]
It's fixed now.
